title: tpm2-software community
email: https://lists.01.org/mailman/listinfo/tpm2
description: >-
  The community around the TPM Software Stack 2.0 and its tpm2-tss open source
  implementation and all the tools and software that build upon it.

theme: minima
#theme: jekyll-theme-cayman

plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - README
